on: 
  workflow_dispatch: 

jobs: 
  hello_world_job: 
    runs-on: ubuntu-latest 
    name: A job to say hello 
    steps: 
      - name: Checkout repository content
        uses: actions/checkout@v4
        with:
          ref: main 

      - name: Hello world action step 
        id: hello 
        uses: ./.testdocker/hello-world-docker-action 
        with: 
          who-to-greet: 'Mona the Octocat' 

      - name: Get the output time 
        run: echo "The time was ${{ steps.hello.outputs.time }}" 

      - name: Upload Build Artifacts 
        uses: actions/upload-artifact@v4 
        with: 
          name: workspace_artifacts 
          path: ${{ github.workspace }}
